# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-26 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parking_id', models.CharField(default='2542679760274f8b9e049d012650e592', max_length=32, primary_key=True, serialize=False)),
                ('parking_name', models.CharField(db_index=True, max_length=100)),
                ('parking_address', models.CharField(db_index=True, max_length=100, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_company', to='company.Company')),
            ],
            options={
                'db_table': 'parking',
            },
        ),
    ]
