# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-26 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(default='ea7f860b66ef4711a554fc218bbe601b', max_length=32, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=100)),
                ('company_address', models.CharField(db_index=True, max_length=100, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
